# Generated by Django 5.0.3 on 2024-03-27 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('size', models.FloatField()),
                ('price', models.FloatField()),
                ('availability', models.BooleanField()),
                ('photos', models.ImageField(upload_to='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces_owned', to='user_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingDate', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('adSpace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_booking.adspace')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('paymentStatus', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_payments', to='user_management.user')),
                ('spaceOwnerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_payments', to='user_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('comment', models.TextField()),
                ('adSpace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='space_booking.adspace')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.user')),
            ],
        ),
    ]
