# Generated by Django 5.0.3 on 2024-04-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_booking', '0002_alter_adspace_owner_alter_adspace_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adspace',
            name='photos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
