# Generated by Django 4.2.11 on 2024-04-13 08:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('space_booking', '0005_rename_comment_rating_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='title',
            field=models.CharField(default=datetime.datetime(2024, 4, 13, 8, 50, 12, 305966), max_length=100),
            preserve_default=False,
        ),
    ]
