# Generated by Django 5.0.3 on 2024-05-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_booking', '0007_alter_payment_client_alter_payment_spaceownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='adspace',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
